name: myfitness
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
     - images/onBoard1.png
     - images/nutritionButton.png
     - images/onBoard2.png
     - images/onBoard3.png
     - images/onBoard4.png
     - images/tick.png
     - images/binary.png
     - images/male.png
     - images/female.png
     - images/arth.png
     - images/blood.png
     - images/celiac.png
     - images/diab.png
     - images/heart.png
     - images/none.png 
     - images/nVeg.png 
     - images/veg.png 
     - images/pes.png 
     - images/eAll.png
     - images/chinese.png
     - images/sAVeg.png
     - images/french.png
     - images/italian.png
     - images/greek.png
     - images/spanish.png
     - images/japnese.png 
     - images/lebanese.png
     - images/turkish.png
     - images/thai.png
     - images/frenchToast.png
     - images/plus.png
     - images/profile.png
     - images/RMF.png
     - images/progress.png
     - images/report.png
     - images/work.png
     - images/goal.png
     - images/nutri.png
     - images/appDevices.png
     - images/steps.png
     - images/reminder.png
     - images/notification.png
     - images/editProfile.png
     - images/subscription.png
     - images/delete.png  
     - images/password.png
     - images/privacy.png
     - images/about.png
     - images/logout.png
     - images/indian.png
     - images/pakistani.png
     - images/mexican.png
     - images/egg.png
     - images/diary.png
     - images/bread.png
     - images/peanut.png
     - images/nc.png
     - images/water.png
     - images/cardio.png
     - images/power.png
     - images/stretch.png
     - images/dancing.png
     - images/yoga.png
     - images/highProtien.png
     - images/lowCarbs.png
     - images/logos_apple.png
     - images/recipes.png
     - images/planIcon.png
     - images/camera.png
     - images/sleep.png
     - images/workout.png
     - images/sync.png
     - images/burger.png
     - images/logos_fb.png
     - images/logos_google.png
     - images/goals.svg
     - images/excersice2.png
     - images/clock.png
     - images/fire.png
     - images/food.svg
     - images/exercise.svg
     - images/breakfast.png
     - images/lunch.png
     - images/snack.png
     - images/dinner.png
     - images/dairyBf.png
     - images/dairyLunch.png
     - images/dairyDinner.png
     - images/dairyExercise.png
     - images/dairySnacks.png
     - images/dairyWater.png
     - images/weight.png
     - images/person.png
     - images/cake.png
     - images/entry1.png
     - images/entry2.png
     - images/weightIcon.png
     - images/date.png
     - images/oldNotification.png
     - lib/json files/onBoard.json
     - lib/json files/subscription.json
     - lib/json files/questions.json
     - lib/json files/otp.json
     - lib/json files/homeCards.json
     - lib/json files/meals.json
     - lib/json files/waterIntake.json
     - lib/json files/steps.json
     - lib/json files/weightChart.json
     - lib/json files/stepChart.json
     - lib/json files/dailyExcersice.json
     - lib/json files/explore.json
     - lib/json files/caloriesLeft.json
     - lib/json files/dairyBreakfast.json
     - lib/json files/dairyLunch.json
     - lib/json files/dairySnacks.json
     - lib/json files/dairyExercise.json
     - lib/json files/dairyWater.json
     - lib/json files/dairyDinner.json
     - lib/json files/caloriesExplorer.json
     - lib/json files/nutrientExplorer.json
     - lib/json files/macrosExplorer.json
     - lib/json files/plans.json
     - lib/json files/myPlans.json
     - lib/json files/profile.json
     - lib/json files/goal.json
     - lib/json files/progress.json
     - lib/json files/oldNotifications.json

     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding asets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
    - family: Poppin
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Italic.ttf
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Regular.ttf
        - asset: fonts/Mulish-SemiBold.ttf
        - asset: fonts/Mulish-Italic.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
